aplikacija1/urls.py
# APP URLs

from django.urls import path
from aplikacija1 import views

app_name = 'aplikacija'
urlpatterns = [
    path('', views.index, name='index'),

    path('stranica1/', views.stranica1, name='stranica1'),
    path('stranica2/', views.stranica2, name='stranica2'),
    path('add_student/', views.StudentView.as_view(), name='AddStudent'),
    path('student/', views.studenti, name='studenti'),

    path('student/<int:id>', views.student, name='student'),
    path('student/delete/<int:id>', views.studentDelete, name='studentDelete'),
]

# http://127.0.0.1:8000/

# http://127.0.0.1:8000/admin
# http://127.0.0.1:8000/aplikacija

# http://127.0.0.1:8000/aplikacija
# http://127.0.0.1:8000/aplikacija/stranica1
# http://127.0.0.1:8000/aplikacija/stranica2

# http://127.0.0.1:8000/aplikacija/student/1

primerProjekta/urls.py
# PROJECT URLs

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('aplikacija1.urls')),
    path('todo/', include('todos.urls')),

    path('api/', include('rest_api.urls')),
]

rest_api/urls.py
from django.urls import path
from rest_api import views

app_name = 'rest_api'
urlpatterns = [
    path('category/', views.CategoryListView.as_view(), name='cat_list'),
    path('category/<int:pk>', views.CategoryDetailsView.as_view(), name='cat_details'),
]

todos/urls.py
from django.urls import path
from todos import views

app_name = 'todos'
urlpatterns = [
    path('home', views.home, name='home'),
    path('todos', views.Todos.as_view(), name='todos'),

    path('todos/update/<int:pk>', views.TaskUpdateView.as_view(), name='todos_update'),

    path('todos/delete/<int:pk>', views.TaskDeleteView.as_view(), name='delete_todo'),
    path('todos/done/<int:id>', views.done_todo, name='done_todo'),

    path('category/create', views.CategoryCreateView.as_view(), name='category_create'),

]

aplikacija1/models.py
from django.db import models


# Create your models here.
class Student(models.Model):
    ime = models.CharField(max_length=50)
    prezime = models.CharField(max_length=50)
    starost = models.IntegerField()

    def __str__(self):
        return self.ime + " " + self.prezime

rest_api/models.py
from django.db import models

# Create your models here.

todos/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return f"{self.name} ({len(self.description)})"


class Task(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    done = models.BooleanField(default=False)
    priority = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.title} ({self.priority})"

aplikacija1/forms.py
from django import forms

from aplikacija1.models import Student


class FormStudent(forms.ModelForm):
    #dodatna polja

    class Meta:
        model = Student
        fields = '__all__'

todos/forms.py
from django import forms
from todos.models import Task


class FormTask(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

aplikacija1/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views import View

from aplikacija1.forms import FormStudent
from aplikacija1.models import Student


def index(request):
    return render(request, 'home.html', {})


def stranica1(request):
    return render(request, 'stranica.html', {'poruka': 1})


def stranica2(request):
    return render(request, 'stranica.html', {'poruka': 2})


def studenti(request):
    try:
        s = Student.objects.all()
        return render(request, 'studenti.html', {'studenti': s})
    except:
        raise Http404("Nema studenata")


def student(request, id):
    try:
        s = Student.objects.get(pk=id)
        return render(request, 'student.html', {'student': s})
    except:
        raise Http404("Nema studenta")


def studentDelete(request, id):
    try:
        s = Student.objects.get(pk=id)
        s.delete()
        return HttpResponseRedirect(reverse('aplikacija:studenti'))
    except:
        raise Http404("Nema studenta")


def noviStudent(request):
    if (request.method == 'POST'):
        form = FormStudent(request.POST)
        if (form.is_valid()):
            form.save()
            return HttpResponseRedirect(reverse('aplikacija:studenti'))
        return render(request, 'noviStudent.html', {'form': form})
    else:
        form = FormStudent()
        return render(request, 'noviStudent.html', {'form': form})


class StudentView(View):
    def get(self, request):
        form = FormStudent()
        return render(request, 'noviStudent.html', {'form': form})

    def post(self, request):
        form = FormStudent(request.POST)
        if (form.is_valid()):
            form.save()
            return HttpResponseRedirect(reverse('aplikacija:studenti'))
        return render(request, 'noviStudent.html', {'form': form})

rest_api/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework import generics
from rest_api.serializers import CategorySerializer
from todos.models import Category


class CategoryDetailsView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


class CategoryListView(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

todos/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, DeleteView

from todos.forms import FormTask
from todos.models import Task, Category


def home(request):
    return render(request, 'todosHome.html', {})


def delete_todo(request, id):
    try:
        t = Task.objects.get(pk=id)
        t.delete()
        return HttpResponseRedirect(reverse('todos:todos'))
    except:
        raise Http404("Nema taska, sa ovim ID-em")


def done_todo(request, id):
    try:
        t = Task.objects.get(pk=id)
        t.done = not t.done
        t.save()
        return HttpResponseRedirect(reverse('todos:todos'))
    except:
        raise Http404("Nema taska, sa ovim ID-em")


class Todos(View):
    def get(self, request):
        tasks = Task.objects.all()
        form = FormTask()
        return render(request, 'todos.html', {'tasks': tasks, 'form': form})

    def post(self, request):
        form = FormTask(request.POST)
        if form.is_valid():
            form.save()

            form = FormTask()
            tasks = Task.objects.all()
            return render(request, 'todos.html', {'tasks': tasks, 'form': form})
        tasks = Task.objects.all()
        return render(request, 'todos.html', {'tasks': tasks, 'form': form})


class CategoryCreateView(CreateView):
    model = Category
    fields = '__all__'
    template_name = 'form.html'
    success_url = reverse_lazy('todos:todos')


class TaskUpdateView(UpdateView):
    model = Task
    fields = '__all__'
    template_name = 'form.html'
    success_url = reverse_lazy('todos:todos')


class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('todos:todos')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <base href="{% static '' %}">
    <meta charset="UTF-8">
    <title>{% block title %} Osnovni naslov {% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>

<img src="img/logo.png">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNavDropdown">
            <ul class="navbar-nav mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aplikacija:index' %}">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aplikacija:stranica1' %}">Stranica 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aplikacija:stranica2' %}">Stranica 2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'aplikacija:studenti' %}">Studenti</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todos:todos' %}">TODO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todos:category_create' %}">Category add</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %}Podrazumevana vrednost{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm" class="btn btn-outline-danger">
    </form>
{% endblock %}

templates/form.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <div class="form-group m-3">
                <label>{{ f.label_tag }}</label>
                {{ f }}
            </div>
        {% endfor %}
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
{% endblock %}

templates/home.html
{%  extends "base.html" %}

{% block title %} Home page {% endblock  %}

{% block content %}
    OVO JE HOME PAGE!
{% endblock %}

templates/noviStudent.html
{% extends "base.html" %}

{% block title %} Dodavanje studenta {{ poruka }} {% endblock %}

{% block content %}
    <div class="card" style="width: 50%;">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}

                {% for f in form %}
                <div class="form-group row m-3">
                    <label class="col-2">{{ f.label_tag }}</label>
                    <div class="col-10">
                        {{ f }}
                    </div>
                </div>
                {% endfor %}
                <input type="submit" value="Submit" class="btn btn-primary">
            </form>
        </div>
    </div>
{% endblock %}

templates/stranica.html
{%  extends "base.html" %}

{% block title %} Stranica {{ poruka }} {% endblock  %}

{% block content %}
    Stranica {{ poruka }}
{% endblock %}

templates/student.html
{% extends "base.html" %}

{% block title %}Student {{ student.ime }}{% endblock %}

{% block content %}
    {% if student %}
        <h1>{{ student.ime }}</h1>
        <h2>{{ student.prezime }}</h2>
        <h3>{{ student.starost }}</h3>

        <a
                href="{% url 'aplikacija:studentDelete' student.id %}"
                class="btn btn-danger mb-2"
                role="button"
                aria-pressed="true">
            Obrisi studenta
        </a>

    {% else %}
        <p>NEMA STUDENT</p>
    {% endif %}
{% endblock %}

templates/studenti.html
{% extends "base.html" %}

{% block title %}Studenti{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">

            <a
                    href="{% url 'aplikacija:AddStudent' %}"
                    class="btn btn-primary mb-2"
                    role="button"
                    aria-pressed="true">
                Dodaj studenta
            </a>

            {% if studenti %}
                <ul class="list-group">
                    {% for student in studenti %}
                        <li class="list-group-item">
                            <a class="nav-link text-dark" href="{% url 'aplikacija:student' student.id %}">
                                {{ student.ime }} {{ student.prezime }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>NEMA STUDENTA</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/todos.html
{% extends "base.html" %}

{% block title %} TODO {% endblock %}

{% block content %}

    <div class="container mt-4">
        <div class="row">
            <div class="col-8 shadow rounded m-2 justify-content-center">
                {#                <div class="d-flex flex-row justify-content-center">#}

                {% for task in tasks %}

                    {% if forloop.counter0|divisibleby:3 %}
                        <div class="d-flex flex-row justify-content-center">
                    {% endif %}

                <div class="card m-2" style="width: 18rem;">
                    <div class="card-body">


                        {% if task.priority == 0 %}
                            <h5 class="card-title bg-light">{{ task.title }}</h5>
                        {% elif task.priority == 1 %}
                            <h5 class="card-title bg-info">{{ task.title }}</h5>
                        {% elif task.priority == 2 %}
                            <h5 class="card-title bg-primary">{{ task.title }}</h5>
                        {% elif task.priority == 3 %}
                            <h5 class="card-title bg-success">{{ task.title }}</h5>
                        {% elif task.priority == 4 %}
                            <h5 class="card-title bg-warning">{{ task.title }}</h5>
                        {% elif task.priority == 5 %}
                            <h5 class="card-title bg-danger">{{ task.title }}</h5>
                        {% else %}
                            <h5 class="card-title bg-dark">{{ task.title }}</h5>
                        {% endif %}


                        {% if task.done %}
                            <del><p class="card-text">{{ task.description }}</p></del>
                        {% else %}
                            <p class="card-text">{{ task.description }}</p>
                        {% endif %}

                        <div class="d-flex flex-row justify-content-around">
                            <a
                                    class="btn btn-outline-success"
                                    href="{% url 'todos:done_todo' task.id %}"
                                    role="button">

                                {% if task.done %}
                                    Undone
                                {% else %}
                                    Done
                                {% endif %}

                            </a>
                            <a
                                    class="btn btn-outline-danger"
                                    href="{% url 'todos:delete_todo' task.id %}"
                                    role="button">Delete
                            </a>
                            <a
                                    class="btn btn-outline-warning"
                                    href="{% url 'todos:todos_update' task.id %}"
                                    role="button">Edit
                            </a>


                        </div>

                    </div>
                </div>

                {% if forloop.counter0|add:-2|divisibleby:3 %}
                    </div>
                {% endif %}

                {% endfor %}

                {% if not tasks|length|divisibleby:3 %}
                    </div>
                {% endif %}


        </div>
        <div class="col-3 shadow rounded m-2 p-2">
            <form method="post">
                {% csrf_token %}
                {% for f in form %}
                    <div class="form-group m-3">
                        <label>{{ f.label_tag }}</label>
                        {{ f }}
                    </div>
                {% endfor %}
                <input type="submit" value="Dodaj" class="btn btn-primary">
            </form>
        </div>
    </div>
    </div>


    {#    {% if tasks %}#}
    {#        <div class="card">#}
    {#            {% for task in tasks %}#}
    {#                <div class="d-flex flex-row justify-content-center">#}
    {#                    <div class="card" style="width: 18rem;">#}
    {#                        <div class="card-body">#}
    {#                            <h5 class="card-title"> {{ task.title }} </h5>#}
    {#                            <p class="card-text"> {{ task.description }} </p>#}
    {#                        </div>#}
    {#                    </div>#}
    {#                </div>#}
    {#            {% endfor %}#}
    {#        </div>#}
    {#    {% else %}#}
    {#        <p>Nema zadataka!</p>#}
    {#    {% endif %}#}

{% endblock %}

templates/todos/category_form.html
{% extends "base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% for f in form %}
            <div class="form-group m-3">
                <label>{{ f.label_tag }}</label>
                {{ f }}
            </div>
        {% endfor %}
        <input type="submit" value="Save" class="btn btn-primary">
    </form>
{% endblock %}

templates/todosHome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TODOs</title>
</head>
<body>

Ovo je TODOs aplikacija!

</body>
</html>